apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../crd
- ./nvidia-dcgm-mock-exporter
namespace: odh
images:
- name: quay.io/opendatahub/odh-dashboard
  newName: quay.io/opendatahub/odh-dashboard
  newTag: nightly
